### PR TITLE
Implement minimal server, prepare tokens for automatic rotation

### PR DESCRIPTION
**Pull request by jnv**
Since the demo server was taken from the generic social media demo, I wanted to trim the fat to better show the authentication flow and to also test out stateless auth.

Furthermore, Twitter's tokens are quite volatile: we need to store both access and refresh token upon each token refresh, so it doesn't make sense to treat them as static configuration in `.env`. Instead I propose storing tokens in mutable `tokens.json` file to keep them easily up to date.

In a follow up PRs I'd like to:

- update scripts to read tokens from the PR
- implement token refresh using the newly published profile
- get rid of the express-session dependency

Don't mind the commit messages, I'd like to squash the PR once accepted.

### CODE REVIEW

**Review by janhalama — COMMENTED** [review]
I like it. You managed to make it really simple. 👍 

The only think I miss is update of the scripts so that they use access token from tokens.json file instead of env variable. Now if I follow the instructions in readme, I will fail to run the scripts.

**Comment by janhalama** [comment]
Oh I see that you have the update scheduled in followup PR, but I think it should be done here.

**Comment by jnv** [comment]
@janhalama You are right, added, thanks!

**Review by janhalama — APPROVED** [review]
LGTM 👍

**Pull request merged**
